### ISSUE TITLE
Tutorial 4  - Add search

### ISSUE THREAD

**Issue by indcoder** [dotnet-presentations/aspnetcore-for-beginners#11]
Was going through the Tutorials before .netConf 2018, found a broken link in Tutorial 3
https://github.com/dotnet-presentations/aspnetcore-for-beginners/pull/10

And after updating  that link and after completing that tutorial, I moved to Tutorial 4 , and the tutorial seems to be missing a few instructions. Kindly please check. Cheers.

**Comment by jongalloway** [comment]
Fixed by #10
