### ISSUE TITLE
Prerequisites tutorial links are not correct

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet-presentations/aspnetcore-for-beginners#13]
Links to tutorials in Prerequisites for the following docs are not correct:

 - [VS tutorial 3](https://github.com/dotnet-presentations/aspnetcore-for-beginners/blob/master/Tutorial/3-Update%20Pages/update-VS.md)
- [VS tutorial 4](https://github.com/dotnet-presentations/aspnetcore-for-beginners/blob/master/Tutorial/4-Add%20Search/SearchPage-VS.md)
 - [VS Code tutorial 3](https://github.com/dotnet-presentations/aspnetcore-for-beginners/blob/master/Tutorial/3-Update%20Pages/update.md)
 - [VS Code tutorial 4](https://github.com/dotnet-presentations/aspnetcore-for-beginners/blob/master/Tutorial/4-Add%20Search/SearchPage-VS.md)

I can send a PR later, after I submit the PR that I'm currently working on.

**Comment by jongalloway** [comment]
Fixed by #15
