### ISSUE TITLE
dotnet ef command when .netcore 3.0 installed

### ISSUE THREAD

**Issue by LouisT123** [dotnet-presentations/aspnetcore-for-beginners#16]
On my machine .netcore 2.2 and .netcore 3.0 preview installed. When I ran through the tutorial, I was getting error about `dotnet ef` command not being found. I installed the `dotnet-ef` global tool and it worked. 
After uninstalling .netcore 3.0 and removing `dotnet-ef` global tool I was able to run `dotnet ef` commands without needing the global tool. 

We should consider adding a note for users with .netcore 3.0 installed, letting them know to install `dotnet-ef` global tool. 

cc @sayedihashimi

**Comment by LouisT123** [comment]
I'm happy to send a PR for these changes if we agree that's what we want.

**Comment by mairaw** [comment]
This issue seems stale, and the workshop has just been updated to .NET 6. Closing for that reason.

If this is still a problem, please reopen the issue.
